version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./etc/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge

  php:
    build: ./etc/php
    volumes:
      - .:/var/www/html
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - bridge

networks:
    bridge:
        driver: bridge