services:
    api.taxonsproducts:
        class: ApiBundle\Services\TaxonsProductsService
        arguments: ["@api.client"]
    api.client:
        class: ApiBundle\Services\ClientService
        arguments: []
    api.facebook:
        class: ApiBundle\Services\FacebookService
        arguments: ['@api.client']