services:
    api.taxonsProducts:
        class: ApiBundle\Services\TaxonsProductsService
        arguments: ["api.client"]
    api.client:
        class: ApiBundle\Services\ClientService
        arguments: []
